name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: sample
          root_file: |
            proposal.tex
            proposal-libertine.tex

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          latexmk_use_xelatex: true
          working_directory: sample
          root_file: |
            proposal-xetex.tex
            proposal-libertine-xetex.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          path: |
            sample/*.pdf
